name       : libpcre
version    : 8.39
release    : 11
source     :
    - ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz : ccdf7e788769838f8285b3ee672ed573358202305ee361cfec7a4a4fb005bbc7
license    :
    - BSD-3-Clause
summary    : pcre (Perl Compatible Regular Expressions)
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - bzip2-32bit-devel
    - libstdc++-32bit
    - pkgconfig32(zlib)
optimize   : speed
emul32     : yes
patterns   :
    - docs :
        - /usr/share/doc/pcre/html/
        - /usr/share/man/man3
description: |
    pcre is a library of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. It has its own API and wrappers that correspond to the POSIX regular expression API.
setup      : |
    %configure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --disable-static \
               --enable-pcre16 \
               --enable-pcre32 \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make clean
