name       : libpcre
version    : '8.42'
release    : 18
source     :
    - https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.bz2 : 2cd04b7c887808be030254e8d77de11d3fe9d4505c39d4b15d2664ffe8bf9301
license    : BSD-3-Clause
component  : system.base
summary    : Perl Compatible Regular Expressions
description: |
    pcre is a library of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. It has its own API and wrappers that correspond to the POSIX regular expression API.
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(zlib)
    - bzip2-32bit-devel
patterns   :
    - docs :
        - /usr/share/doc/pcre/html/
        - /usr/share/man/man3
setup      : |
    %apply_patches
    %configure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --enable-pcre16 \
               --enable-pcre32 \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
