name        : libpcre
version     : 8.37
release     : 6
source     :
    - http://downloads.sourceforge.net/pcre/pcre-8.37.tar.bz2 : 51679ea8006ce31379fb0860e46dd86665d864b5020fc9cd19e71260eef4789d
license     :
    - BSD-3-Clause
summary     : pcre (Perl Compatible Regular Expressions)
builddeps    :
    - glibc-32bit-devel
    - libgcc-32bit
    - bzip2-32bit-devel
    - libstdc++-32bit
    - pkgconfig32(zlib)
emul32      : yes
description : |
    pcre is a library of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. It has its own API and wrappers that correspond to the POSIX regular expression API.
setup      : |
    if [[ ! -e .patched ]]; then
        %patch -p1 < $pkgfiles/0001-Fix-forward-reference-offset-bug.patch
        %patch -p1 < $pkgfiles/0002-Fix-forward-referencing-bugs.patch
        %patch -p1 < $pkgfiles/0003-Fix-buffer-overflow-for-repeated-conditional-when-re.patch
        %patch -p1 < $pkgfiles/0004-Fix-buffer-overflow-for-named-recursive-back-referen.patch
        %patch -p1 < $pkgfiles/0005-Fix-named-forward-reference-to-duplicate-group-numbe.patch
        %patch -p1 < $pkgfiles/0006-Fix-buffer-overflow-for-lookbehind-within-mutually-r.patch
        %patch -p1 < $pkgfiles/0007-JIT-compiler-update.patch
        %patch -p1 < $pkgfiles/0008-Fix-another-buffer-overflow.patch
        %patch -p1 < $pkgfiles/0009-Add-integer-overflow-check-to-n-code.patch
        %patch -p1 < $pkgfiles/0010-Fix-table-entry-for-l-in-EBCDIC-environments.patch
        %patch -p1 < $pkgfiles/0011-Fix-overflow-when-ovector-has-size-1.patch
        %patch -p1 < $pkgfiles/0012-Fix-group-empty-match-bug.patch
        %patch -p1 < $pkgfiles/cve-2015-5073.patch
        touch .patched
        autoreconf -vfi
    fi
    %configure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
