name       : libpcre
version    : '8.44'
release    : 19
source     :
    - https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz : aecafd4af3bd0f3935721af77b889d9024b2e01d96b58471bd91a3063fb47728
license    : BSD-3-Clause
component  : system.base
summary    : Perl Compatible Regular Expressions
description: |
    pcre is a library of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. It has its own API and wrappers that correspond to the POSIX regular expression API.
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(zlib)
    - bzip2-32bit-devel
patterns   :
    - docs :
        - /usr/share/doc/pcre/html/
        - /usr/share/man/man3
setup      : |
    %apply_patches
    %configure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --enable-pcre16 \
               --enable-pcre32 \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
