name       : libpcre
version    : 8.38
release    : 8
source     :
    - http://downloads.sourceforge.net/pcre/pcre-8.38.tar.bz2 : b9e02d36e23024d6c02a2e5b25204b3a4fa6ade43e0a5f869f254f49535079df
license    :
    - BSD-3-Clause
summary    : pcre (Perl Compatible Regular Expressions)
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - bzip2-32bit-devel
    - libstdc++-32bit
    - pkgconfig32(zlib)
optimize   : speed
emul32     : yes
patterns   :
    - docs:
        - /usr/share/doc/pcre/html/
        - /usr/share/man/man3
description: |
    pcre is a library of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. It has its own API and wrappers that correspond to the POSIX regular expression API.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2016-1283.patch
    %patch -p1 < $pkgfiles//security/cve-2016-3191.patch
    autoreconf -vfi
    %configure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
