name       : libpcre
version    : '8.41'
release    : 16
source     :
    - https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.bz2 : e62c7eac5ae7c0e7286db61ff82912e1c0b7a0c13706616e94a7dd729321b530
license    : BSD-3-Clause
summary    : pcre (Perl Compatible Regular Expressions)
builddeps  :
    - pkgconfig32(zlib)
    - bzip2-32bit-devel
optimize   : speed
component  : system.base
emul32     : yes
patterns   :
    - docs :
        - /usr/share/doc/pcre/html/
        - /usr/share/man/man3
description: |
    pcre is a library of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. It has its own API and wrappers that correspond to the POSIX regular expression API.
setup      : |
    %apply_patches
    %configure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --disable-static \
               --enable-pcre16 \
               --enable-pcre32 \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
